[pytest]
testpaths = tests
addopts = -ra --strict-config --strict-markers
filterwarnings =
    error::DeprecationWarning:app(\.|$)
    ignore:.*asyncio\.iscoroutinefunction.*:DeprecationWarning:fastapi\.routing
